name: brainybubbles
description: Brainy Bubbles — simple bubble popping game with music and pops
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

# If you’re on a much older Flutter/Dart SDK, tell me and I’ll adjust this.
# This works well with current stable Flutter 3.x + Dart 3.x.

dependencies:
  flutter:
    sdk: flutter

  # Sound: background music + pop SFX
  audioplayers: 5.2.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Make sure these files exist with these exact names and paths:
  assets:
    - assets/audio/brainy_bubbles_bg.mp3
    - assets/audio/pop_hi.mp3
    - assets/audio/pop_lo.mp3
