name: brainybubbles
description: Brainy Bubbles Flutter WebView wrapper
publish_to: 'none' # this prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # WebView support
  webview_flutter: ^4.13.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.14.0

  # Audio player
  audioplayers: ^5.2.1

  # Misc Flutter dependencies
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/audio/brainy_bubbles_bg.mp3
    - assets/audio/pop_hi.mp3
    - assets/audio/pop_lo.mp3
